import ScrollToTop from "./components/Helper/ScrollToTop";
import Provider from "./components/HOC/Provider";
import Footer from "./components/Home/Footer/Footer";
import ResponsiveNav from "./components/Home/navbar/ResponsiveNav";
import "./globals.css";

export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white text-black dark:bg-black dark:text-white">
        <Provider>
          <ResponsiveNav/>
          {children}
          <Footer />
          <ScrollToTop />
        </Provider>
      </body>
    </html>
  );
}


